title: Azure Developer College
description: Collection of resources for developers to get started on Azure
themeConfig:
  repo: "azuredevcollege/azuredevcollege.github.io"
  editLinks: true
  search: false
